[pipelines.forums_new_forum]
metadata.version = "1.0"
pipeline.source_connectors = [
    [
        ["@connector", "http_rest"],
        ["@instance", "http_rest_inst_forum"],
        ["http.listen", "0.0.0.0:8081"],
        ["http.method", "post"],
        ["http.path", "/forums/new"],
        ["@mapping", [
            ["http", "", [
                ["body", "forum", [
                    ["forum_name", "forum_name"],
                    ["forum_description", "forum_description"],
                    ["parent_forum_id", "parent_forum_id"],
                ]]
            ]]
        ], [
            ["", "http", [
                ["forum", "body", [
                    ["forum_id", "forum_id"],
                ]]
            ]]
        ], [
            { "error_key" = "check_parameter_failed", "error_message" = "http/body/message", "http/status" = "400" },
        ]],
    ],
]
pipeline.steps = [
    [
        ["@flow", "forum_new_forum_validation"]
    ],
    [
        ["@case-non-empty", "forum/parent_forum_id"],
        ["@flow", "&forum_datasource"],
        ["@instance", "database_forum"],
        ["database.operation", "query"],
        ["database.sql", "select forum_id from \"forums\" where forum_id = $1"],
        ["@mapping", [
            ["forum", "", [
                ["parent_forum_id", "sql.args.0"],
            ]]
        ], [
            ["", "database", [
                ["", "forum", [
                    ["sql.result.0", "parent_forum_id"],
                ]]
            ]]
        ]],
    ],
    [
        ["@case-non-empty", "forum/parent_forum_id"],
        ["@flow", "forum_check_existing"],
    ],
    [
        ["@flow", "forum_generate_forum_data"],
    ],
    [
        ["@flow", "&forum_datasource"],
        ["@instance", "database_forum"],
        ["database.operation", "exec"],
        ["database.sql", "insert into forums (forum_id, forum_name, forum_description, parent_forum_id, status, time_created, time_updated) values ($1, $2, $3, $4, $5, $6, $7);"],
        ["@mapping", [
            ["forum", "", [
                ["forum_id", "sql.args.0"],
                ["forum_name", "sql.args.1"],
                ["forum_description", "sql.args.2"],
                ["parent_forum_id", "sql.args.3"],
                ["status", "sql.args.4"],
                ["time_created", "sql.args.5"],
                ["time_updated", "sql.args.6"],
            ]]
        ], [
            ["", "debugging", [
                ["", "database", [
                    ["sql.affected_row_count", "affected_row_count"],
                ]]
            ]]
        ]],
    ],
]

[flows.forum_generate_forum_data]
out = [
    ["", "forum", [
        ["forum_id", "forum_id"],
        ["status", "status"],
        ["time_created", "time_created"],
        ["time_updated", "time_updated"],
    ]]
]
flow.steps = [
    { "@uuid" = ["forum_id"] },
    { "@assign" = ["status", 0] },
    { "@set_current_unix_timestamp" = ["time_created"] },
    { "@set_current_unix_timestamp" = ["time_updated"] },
]

[flows.forum_check_existing]
in = [
    ["database", "", [
        ["forum", "", [
            ["parent_forum_id", "parent_forum_id"]
        ]]
    ]]
]
flow.steps = [
    { "@check_not_blank_break" = ["parent_forum_id", "check_parameter_failed", "parent forum is not found"] },
]

[flows.forum_new_forum_validation]
in = [
    ["forum", "", [
        ["forum_name", "forum_name"],
        ["forum_description", "forum_description"],
    ]]
]
flow.steps = [
    { "@check_not_blank_break" = ["forum_name", "check_parameter_failed", "forum_name is empty"] },
    { "@check_not_blank_break" = ["forum_description", "check_parameter_failed", "forum_description is empty"] },
]
