[pipelines.forums_new_forum]
metadata.version = "1.0"
pipeline.source_connectors = [
    [
        ["@connector", "http_rest"],
        ["@mapping", "http_inst"],
        ["http.listen", "0.0.0.0:8081"],
        ["http.method", "post"],
        ["http.path", "/forums/new"],
    ],
]
pipeline.steps = [
    [
        ["@flow", "forum_new_forum_validation"]
    ],
    [
        ["@case-non-empty", "forum/parent_forum_id"],
        ["@flow", "&database_postgres"],
        ["@mapping", "query_forum"],
        ["database.connect_string", "postgres://admin:admin@192.168.1.111:25432/forum"],
        ["database.operation", "query"],
        ["database.sql", "select forum_id from \"forums\" where forum_id = $1"],
    ],
    [
        ["@case-non-empty", "forum/parent_forum_id"],
        ["@flow", "forum_check_existing"],
    ],
    [
        ["@flow", "forum_generate_forum_data"],
    ],
    [
        ["@flow", "&database_postgres"],
        ["@mapping", "forum_insert"],
        ["database.connect_string", "postgres://admin:admin@192.168.1.111:25432/forum"],
        ["database.operation", "exec"],
        ["database.sql", "insert into forums (forum_id, forum_name, forum_description, parent_forum_id, status, time_created, time_updated) values ($1, $2, $3, $4, $5, $6, $7);"],
    ],
]
connector_mapping.http_inst.req = [
    ["forum/forum_name", "http/body/forum_name"],
    ["forum/forum_description", "http/body/forum_description"],
    ["forum/parent_forum_id", "http/body/parent_forum_id"],
]
connector_mapping.http_inst.res = [
    ["forum/forum_id", "http/body/forum_id"],
]
connector_mapping.http_inst.err_simple = [
    { "error_key" = "check_parameter_failed", "error_message" = "http/body/message", "http/status" = "400" },
]
connector_mapping.query_forum.req = [
    ["forum/parent_forum_id", "sql.args.0"],
]
connector_mapping.query_forum.res = [
    ["database/forum/parent_forum_id", "sql.result.0"],
]
connector_mapping.forum_insert.req = [
    ["forum/forum_id", "sql.args.0"],
    ["forum/forum_name", "sql.args.1"],
    ["forum/forum_description", "sql.args.2"],
    ["forum/parent_forum_id", "sql.args.3"],
    ["forum/status", "sql.args.4"],
    ["forum/time_created", "sql.args.5"],
    ["forum/time_updated", "sql.args.6"],
]
connector_mapping.forum_insert.res = [
    ["debugging/database/affected_row_count", "sql.affected_row_count"],
]

[flows.forum_generate_forum_data]
in = [
]
out = [
    ["forum_id", "forum/forum_id"],
    ["status", "forum/status"],
    ["time_created", "forum/time_created"],
    ["time_updated", "forum/time_updated"],
]
flow.steps = [
    { "@uuid" = ["forum_id"] },
    { "@assign" = ["status", 0] },
    { "@set_current_unix_timestamp" = ["time_created"] },
    { "@set_current_unix_timestamp" = ["time_updated"] },
]

[flows.forum_check_existing]
in = [
    ["database/forum/parent_forum_id", "parent_forum_id"],
]
flow.steps = [
    { "@check_not_blank_break" = ["parent_forum_id", "check_parameter_failed", "parent forum is not found"] },
]

[flows.forum_new_forum_validation]
in = [
    ["forum/forum_name", "forum_name"],
    ["forum/forum_description", "forum_description"],
]
flow.steps = [
    { "@check_not_blank_break" = ["forum_name", "check_parameter_failed", "forum_name is empty"] },
    { "@check_not_blank_break" = ["forum_description", "check_parameter_failed", "forum_description is empty"] },
]
